using System;
using System.Collections.Generic;
using System.IO;
using TMPro;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

[InitializeOnLoad]
public static class IGSDemoSceneBuilder
{
    private const string ScenePath = "Assets/Scenes/IGS.unity";
    private const string MarkerPath = "Assets/Scenes/IGS_DemoNeodgmFont_v2.marker.txt";
    private const string FontPath = "Assets/Fonts/neodgm SDF.asset";

    static IGSDemoSceneBuilder()
    {
        EditorSceneManager.sceneOpened -= HandleSceneOpened;
        EditorSceneManager.sceneOpened += HandleSceneOpened;
        EditorApplication.delayCall += TryBuildActiveScene;
    }

    [MenuItem("Tools/Wheel of Fortune/IGS 데모 다시 생성")]
    public static void RebuildFromMenu()
    {
        if (File.Exists(MarkerPath))
        {
            File.Delete(MarkerPath);
            AssetDatabase.Refresh();
        }

        GameObject existing = GameObject.Find("IGS Demo Preview Canvas");
        if (existing != null)
        {
            UnityEngine.Object.DestroyImmediate(existing);
        }

        TryBuildActiveScene();
    }

    private static void HandleSceneOpened(Scene scene, OpenSceneMode mode)
    {
        TryBuild(scene);
    }

    private static void TryBuildActiveScene()
    {
        TryBuild(SceneManager.GetActiveScene());
    }

    private static void TryBuild(Scene scene)
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode || scene.path != ScenePath
            || File.Exists(MarkerPath))
        {
            return;
        }

        GameObject existing = GameObject.Find("IGS Demo Preview Canvas");
        if (existing != null)
        {
            UnityEngine.Object.DestroyImmediate(existing);
        }

        BuildPreview();
        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene);
        File.WriteAllText(MarkerPath, "IGS demo preview generated by IGSDemoSceneBuilder.\n");
        AssetDatabase.ImportAsset(MarkerPath);
        Debug.Log("IGS 데모 미리보기 Canvas와 경로 노드를 생성했습니다.");
    }

    private static void BuildPreview()
    {
        GameObject canvasObject = new GameObject(
            "IGS Demo Preview Canvas",
            typeof(RectTransform),
            typeof(Canvas),
            typeof(CanvasScaler),
            typeof(GraphicRaycaster));
        Canvas canvas = canvasObject.GetComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        CanvasScaler scaler = canvasObject.GetComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1080f, 1920f);

        GameObject background = CreateUI("Background", canvasObject.transform, typeof(Image));
        Stretch(background.GetComponent<RectTransform>());
        background.GetComponent<Image>().color = new Color(0.055f, 0.07f, 0.11f, 1f);

        GameObject title = CreateText("Title", canvasObject.transform, "운명의 수레바퀴 - IGS 데모", 42);
        SetRect(title.GetComponent<RectTransform>(), new Vector2(0f, 850f), new Vector2(900f, 80f));

        GameObject mapPanel = CreateUI("Map Preview", canvasObject.transform, typeof(Image));
        SetRect(mapPanel.GetComponent<RectTransform>(), new Vector2(0f, -40f), new Vector2(960f, 1650f));
        mapPanel.GetComponent<Image>().color = new Color(0.09f, 0.11f, 0.17f, 1f);

        RectTransform mapRect = mapPanel.GetComponent<RectTransform>();
        List<List<RectTransform>> floors = new List<List<RectTransform>>();
        System.Random random = new System.Random(95);

        for (int floor = 0; floor < 8; floor++)
        {
            List<RectTransform> row = new List<RectTransform>();
            int count = floor == 0 ? 3 : floor == 7 ? 2 : random.Next(3, 5);
            for (int index = 0; index < count; index++)
            {
                float x = (index - (count - 1) * 0.5f) * 210f + random.Next(-25, 26);
                float y = -690f + floor * 195f + random.Next(-10, 11);
                int type = floor == 0 ? 0 : floor == 7 ? 2 : random.Next(0, 3);
                RectTransform node = CreatePreviewNode(mapRect, new Vector2(x, y), type);
                row.Add(node);
            }

            floors.Add(row);
        }

        for (int floor = 0; floor < floors.Count - 1; floor++)
        {
            List<RectTransform> fromRow = floors[floor];
            List<RectTransform> toRow = floors[floor + 1];
            for (int index = 0; index < fromRow.Count; index++)
            {
                int target = Mathf.RoundToInt(index * (toRow.Count - 1f) / Mathf.Max(1, fromRow.Count - 1));
                CreateLine(mapRect, fromRow[index].anchoredPosition, toRow[target].anchoredPosition);
                if (target + 1 < toRow.Count && index % 2 == 0)
                {
                    CreateLine(mapRect, fromRow[index].anchoredPosition, toRow[target + 1].anchoredPosition);
                }
            }
        }

        foreach (List<RectTransform> row in floors)
        {
            foreach (RectTransform node in row)
            {
                node.SetAsLastSibling();
            }
        }

        GameObject legend = CreateText(
            "Legend",
            canvasObject.transform,
            "빨강: 전투     보라: 랜덤     황금: 상점·여관\nPlay 모드에서 실제 경로 선택 가능",
            26);
        SetRect(legend.GetComponent<RectTransform>(), new Vector2(0f, -880f), new Vector2(900f, 90f));
    }

    private static RectTransform CreatePreviewNode(RectTransform parent, Vector2 position, int type)
    {
        GameObject node = CreateUI("Preview Node", parent, typeof(Image));
        RectTransform rect = node.GetComponent<RectTransform>();
        SetRect(rect, position, new Vector2(92f, 92f));
        Image image = node.GetComponent<Image>();
        image.color = type == 0 ? new Color(0.72f, 0.2f, 0.18f, 1f)
            : type == 1 ? new Color(0.48f, 0.25f, 0.72f, 1f)
            : new Color(0.85f, 0.62f, 0.16f, 1f);

        GameObject label = CreateText("Label", node.transform, type == 0 ? "전투" : type == 1 ? "랜덤" : "상점", 20);
        Stretch(label.GetComponent<RectTransform>());
        return rect;
    }

    private static void CreateLine(RectTransform parent, Vector2 from, Vector2 to)
    {
        GameObject line = CreateUI("Preview Connection", parent, typeof(Image));
        RectTransform rect = line.GetComponent<RectTransform>();
        Vector2 direction = to - from;
        rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
        rect.pivot = new Vector2(0.5f, 0.5f);
        rect.anchoredPosition = (from + to) * 0.5f;
        rect.sizeDelta = new Vector2(direction.magnitude, 5f);
        rect.localRotation = Quaternion.Euler(0f, 0f, Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg);
        Image image = line.GetComponent<Image>();
        image.color = new Color(0.65f, 0.68f, 0.75f, 0.75f);
        image.raycastTarget = false;
        rect.SetAsFirstSibling();
    }

    private static GameObject CreateText(string name, Transform parent, string value, int fontSize)
    {
        GameObject result = CreateUI(name, parent, typeof(TextMeshProUGUI));
        TextMeshProUGUI text = result.GetComponent<TextMeshProUGUI>();
        text.font = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(FontPath);
        text.text = value;
        text.fontSize = fontSize;
        text.alignment = TextAlignmentOptions.Center;
        text.color = Color.white;
        return result;
    }

    private static GameObject CreateUI(string name, Transform parent, params Type[] components)
    {
        List<Type> types = new List<Type> { typeof(RectTransform) };
        types.AddRange(components);
        GameObject result = new GameObject(name, types.ToArray());
        result.transform.SetParent(parent, false);
        return result;
    }

    private static void Stretch(RectTransform rect)
    {
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
    }

    private static void SetRect(RectTransform rect, Vector2 position, Vector2 size)
    {
        rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.5f);
        rect.pivot = new Vector2(0.5f, 0.5f);
        rect.anchoredPosition = position;
        rect.sizeDelta = size;
    }
}
